---
AWSTemplateFormatVersion: '2010-09-09'
Description: Magento 2.1 Elasticache Template (qs-1qup6raa9)
Parameters:
  ElastiCacheAutomaticFailover:
    AllowedValues:
    - 'true'
    - 'false'
    Default: 'true'
    Description: Select true/false to setup Automatic Failover
    Type: String
  ElastiCacheNodeType:
    ConstraintDescription: Must select a valid cache instance type.
    Default: cache.m5.large
    Description: The name of the compute and memory capacity class of the ElastiCache
      instance.
    Type: String
  ElastiCacheNodes:
    ConstraintDescription: must be between 2 and 5
    Default: '2'
    Description: Number of nodes in the ElastiCache cluster
    MaxValue: '5'
    MinValue: '2'
    Type: Number
  ElastiCacheSecurityGroup:
    Description: ElastiCache Security Group
    Type: AWS::EC2::SecurityGroup::Id
  Subnet1ID:
    Description: The ID of the private subnet in Availability Zone 1.
    Type: 'AWS::EC2::Subnet::Id'
  Subnet2ID:
    Description: The ID of the private subnet in Availability Zone 2.
    Type: 'AWS::EC2::Subnet::Id'
Resources:
  ElastiCacheSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: Subnets available for the Redis Cache Instance (AWS Quick Start)
      SubnetIds:
        - !Ref Subnet1ID
        - !Ref Subnet2ID
  ElastiCacheCluster:
    Type: AWS::ElastiCache::ReplicationGroup
    Properties:
      ReplicationGroupDescription: ElastiCache Cluster (AWS Quick Start)
      AutomaticFailoverEnabled: !Ref ElastiCacheAutomaticFailover
      CacheNodeType: !Ref ElastiCacheNodeType
      CacheSubnetGroupName: !Ref ElastiCacheSubnetGroup
      Engine: redis
      NumCacheClusters: !Ref ElastiCacheNodes
      SecurityGroupIds:
      - !Ref ElastiCacheSecurityGroup
Outputs:
  ElastiCacheEndpoint:
    Description: ElastiCache address
    Value: !GetAtt ElastiCacheCluster.PrimaryEndPoint.Address
...
